config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'sessions#new'
  resources :users, only: [:new, :index, :create]
  get 'chatroom',to: 'chatroom#index'
  get 'login',to: 'sessions#new'
  post 'login',to: 'sessions#create'
  delete 'logout',to: 'sessions#destroy'
  post 'message',to: 'messages#create'
  mount ActionCable.server, at: '/cable'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/message.rb
class Message < ApplicationRecord
  validates :body, presence: true
  belongs_to :user
  scope :custom_display, -> { order(:created_at).last(50) }
end

app/models/user.rb
class User < ApplicationRecord
  has_many :messages
  has_secure_password
  validates :username, length: { minimum: 2, maximum: 20 }, presence: true
  validates :password_digest, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  helper_method :current_user, :logged_in?, :avtar_selector

  private
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def logged_in?
    !!current_user
  end

  def redirect_if_logged_in
    if logged_in?
      flash[:error] = "You are already logged in."
      redirect_to chatroom_path
    end
  end

  def require_user
    if !logged_in?
      flash[:error] = "You must be logged in to perform that action."
      redirect_to login_path
    end
  end

  def avtar_selector(user)
    if current_user
      if user.id == 1
        "avtar-beard.png"
      elsif user.username == "anonymous"
        "avtar-anonymous.png"
      else
        "avtar-#{user.id.modulo(3)}.png"
      end
    end
  end
end

app/controllers/chatroom_controller.rb
class ChatroomController < ApplicationController
  before_action :require_user

  def index
    @message = Message.new
    @messages = Message.custom_display
    @user = User.where(online: true)
  end

end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController

  def create
    # byebug
    message = current_user.messages.build(permit_params)
    if message.save
      ActionCable.server.broadcast "chatroom_channel", mod_message: message.body, current_user: current_user.id, user: message.user.id, username: message.user.username, create_at: message.created_at.strftime("%I:%M %p")
    end
  end

  private
  def permit_params
    params.require(:message).permit(:body)
  end

  # def message_render(message)
  #   render(partial: 'message', locals: {message: message})
  # end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  before_action :require_user, only: [:destroy]
  before_action :redirect_if_logged_in, only: [:new, :create]

  def new
  end

  def create
    @user = User.find_by(username: params[:session][:username])
    if @user
      session[:user_id] = @user.id
      User.find(@user.id).update(online: true);
      ActionCable.server.broadcast "online_users_channel", username: @user.username, id: @user.id
      flash[:success] = "You are successfully logged in."
      redirect_to chatroom_path
    else
      flash[:error] = "There was some problem with your login details."
      render 'new'
    end
  end

  def destroy
    @user = User.find(session[:user_id])
    @user.update(online: false);
    session[:user_id] = nil
    ActionCable.server.broadcast "offline_users_channel", id: @user.id
    flash[:success] = "You are successfully logged out."
    redirect_to login_path
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/chatroom/index.html.erb
<%= content_tag "h1", class: "ui inverted icon header", id: "h1-tag-index", data: {current: current_user.id} do%>
Message Me
<% end %>
<div class="content" id="users">
  <div class="" id= "online-users-container">
    <div class= "ui avatar image" id= "search-icon"><i class="search icon"></i></div>
    <%= render partial: 'users/user', locals: { user: @user } %>
  </div>
</div>
<div class="chatbox">
  <div class="rounded-top" id="messages">
    <div class="ui feed" id="message-container">
      <%= render @messages %>
    </div>
  </div>
  <div class= "cover">
    <%= form_for(@message, html: {class: "rounded-text-field", role: "form"}, url: message_path, remote: true) do |f| %>
      <%= f.text_field :body, id: "message_body", placeholder: "Enter your message" %>
      <%= f.button '<i class="rocket icon"></i>'.html_safe, id: "message-button"%>
    <% end %>
  </div>
</div>

app/views/layouts/_messages.html.erb
<% flash.each do |type, content|%>
  <div class="ui <%= type %> message transition" id= "flash-messages">
    <i class="close icon"></i>
    <div class="header">
      <%= content %>
    </div>
  </div>
<% end %>

app/views/layouts/_navigation.html.erb
<div class="ui massive top right attached label" id= "navbar">
  <div class="ui dropdown item">
    <i class="ellipsis vertical icon"></i>
    <div class="menu">
      <% if !logged_in? %>
        <%= link_to "login", login_path, class: "item"%>
      <% else %>
        <%= link_to "logout", logout_path, method: :delete, class: "item"%>
      <% end %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MyChattingApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navigation' %>
    <%= yield %>
  </body>
</html>

app/views/messages/_message.html.erb
<div class="content">
  <div class="summary">
    <% if session[:user_id] == message.user.id%>
      <p class= "ui right grey aligned header" id= "message-box">
        <span class= "" id="time-on-message">
          <%= message.created_at.strftime("%I:%M %p") %>
        </span>
        <span class="ui label" id="my-message-body">
          <%= message.body %>
        </span>
      </p>
    <% else %>
      <p class= "ui left grey aligned header" id= "message-box">
        <span class="ui label" id="frnd-message-body">
          <span class= "" id="username-on-message">
            <em><%= message.user.username %>:</em>
          </span>
          <br>
          <%= message.body %>
        </span>
        <span class= "" id="time-on-message">
          <%= message.created_at.strftime("%I:%M %p") %>
        </span>
      </p>
    <% end %>
  </div>
</div>

app/views/users/_user.html.erb
<% user.each do |user_record| %>
  <div class="item">
    <%=image_tag(avtar_selector(user_record), alt: "profile pic", class: "ui avatar image", id: "profile-pic-online") %>
  </div>
<% end %>